// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/cancel.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'send_server.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`, `from`, `from`, `from`

BigInt encryptedUploadSize({required BigInt size}) => RustLib.instance.api.crateApiSendServerEncryptedUploadSize(size: size);

Future<SendServerConfig> fetchSendServerConfig({required String serverUrl}) =>
    RustLib.instance.api.crateApiSendServerFetchSendServerConfig(serverUrl: serverUrl);

/// Uploads files to a Firefox Send compatible server, emitting progress and
/// the final share URL through [sink].
Stream<RsSendServerUploadEvent> uploadSendServer({
  required List<RsSendServerFile> files,
  required RsSendServerUploadOptions options,
  required RsCancellationToken cancelToken,
}) => RustLib.instance.api.crateApiSendServerUploadSendServer(files: files, options: options, cancelToken: cancelToken);

@freezed
sealed class RsSendServerError with _$RsSendServerError implements FrbException {
  const RsSendServerError._();

  const factory RsSendServerError.invalidUrl() = RsSendServerError_InvalidUrl;
  const factory RsSendServerError.status({
    required int status,
  }) = RsSendServerError_Status;
  const factory RsSendServerError.invalidResponse(
    String field0,
  ) = RsSendServerError_InvalidResponse;
  const factory RsSendServerError.network(
    String field0,
  ) = RsSendServerError_Network;
  const factory RsSendServerError.io(
    String field0,
  ) = RsSendServerError_Io;
  const factory RsSendServerError.cancelled() = RsSendServerError_Cancelled;
  const factory RsSendServerError.crypto() = RsSendServerError_Crypto;
  const factory RsSendServerError.other(
    String field0,
  ) = RsSendServerError_Other;
}

class RsSendServerFile {
  final String name;
  final BigInt size;
  final String? mime;
  final String? filePath;
  final Uint8List? fileBytes;
  final int? fileDescriptor;

  const RsSendServerFile({
    required this.name,
    required this.size,
    this.mime,
    this.filePath,
    this.fileBytes,
    this.fileDescriptor,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ mime.hashCode ^ filePath.hashCode ^ fileBytes.hashCode ^ fileDescriptor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsSendServerFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          mime == other.mime &&
          filePath == other.filePath &&
          fileBytes == other.fileBytes &&
          fileDescriptor == other.fileDescriptor;
}

@freezed
sealed class RsSendServerUploadEvent with _$RsSendServerUploadEvent {
  const RsSendServerUploadEvent._();

  const factory RsSendServerUploadEvent.progress({
    required BigInt sent,
    required BigInt total,
    required double progress,
  }) = RsSendServerUploadEvent_Progress;
  const factory RsSendServerUploadEvent.finished({
    required String id,
    required String url,
    String? password,
  }) = RsSendServerUploadEvent_Finished;
  const factory RsSendServerUploadEvent.failed({
    required RsSendServerError error,
  }) = RsSendServerUploadEvent_Failed;
}

class RsSendServerUploadOptions {
  final String serverUrl;
  final String? password;
  final BigInt downloadLimit;
  final BigInt expireSeconds;

  const RsSendServerUploadOptions({
    required this.serverUrl,
    this.password,
    required this.downloadLimit,
    required this.expireSeconds,
  });

  @override
  int get hashCode => serverUrl.hashCode ^ password.hashCode ^ downloadLimit.hashCode ^ expireSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsSendServerUploadOptions &&
          runtimeType == other.runtimeType &&
          serverUrl == other.serverUrl &&
          password == other.password &&
          downloadLimit == other.downloadLimit &&
          expireSeconds == other.expireSeconds;
}

class SendServerAnonLimits {
  final BigInt maxFileSize;
  final BigInt maxDownloads;
  final BigInt maxExpireSeconds;

  const SendServerAnonLimits({
    required this.maxFileSize,
    required this.maxDownloads,
    required this.maxExpireSeconds,
  });

  @override
  int get hashCode => maxFileSize.hashCode ^ maxDownloads.hashCode ^ maxExpireSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendServerAnonLimits &&
          runtimeType == other.runtimeType &&
          maxFileSize == other.maxFileSize &&
          maxDownloads == other.maxDownloads &&
          maxExpireSeconds == other.maxExpireSeconds;
}

class SendServerConfig {
  final SendServerLimits limits;
  final SendServerDefaults defaults;

  const SendServerConfig({
    required this.limits,
    required this.defaults,
  });

  @override
  int get hashCode => limits.hashCode ^ defaults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is SendServerConfig && runtimeType == other.runtimeType && limits == other.limits && defaults == other.defaults;
}

class SendServerDefaults {
  final Uint64List downloadCounts;
  final Uint64List expireTimesSeconds;
  final BigInt expireSeconds;

  const SendServerDefaults({
    required this.downloadCounts,
    required this.expireTimesSeconds,
    required this.expireSeconds,
  });

  @override
  int get hashCode => downloadCounts.hashCode ^ expireTimesSeconds.hashCode ^ expireSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendServerDefaults &&
          runtimeType == other.runtimeType &&
          downloadCounts == other.downloadCounts &&
          expireTimesSeconds == other.expireTimesSeconds &&
          expireSeconds == other.expireSeconds;
}

class SendServerLimits {
  final SendServerAnonLimits anon;

  const SendServerLimits({
    required this.anon,
  });

  @override
  int get hashCode => anon.hashCode;

  @override
  bool operator ==(Object other) => identical(this, other) || other is SendServerLimits && runtimeType == other.runtimeType && anon == other.anon;
}
